import Link from "next/link"
import { useRouter } from "next/router"
import WikiFrey from "../components/WikiFrey"
import { useEffect } from "react"
import Head from 'next/head'
import Sigils from "../public/sigils/Sigils.js"

const Post = ({post}) => {
 
    const router = useRouter()
    if(router.isFallback){
        return <h1>Loading...</h1>
    }
    console.log(Sigils[post.id])

  return (
    <div>
    <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={Sigils[post.id] ? Sigils[post.id].src : post.region==="Dorne" ? Sigils.None_Dorne.src : Sigils[post.region] ? Sigils[post.region].src : Sigils.None.src}/>
      </Head>
        <div>
            <WikiFrey post={post}/>
        </div>
    </div>
  )
}

export default Post

export async function getStaticProps(context){
    const {params,req, res} = context
    const response = await fetch(`https://copper-chipmunk-gear.cyclic.app/POV/${params.postId}`)
    const data = await response.json()
    console.log(data)

    return {
        props: {
            post: data
        }
    }
}

export const getStaticPaths = async () => {
       const response = await fetch(`https://copper-chipmunk-gear.cyclic.app/POV/`)
       const data = await response.json()
       
       const paths = data.map((post) => {
           return {
               params: {
                   postId: `${post.id}`
            }
        }
       })
       
       return {
           paths,
           fallback: false
    }
}
