import Link from "next/link"
import Image from "next/image"
import Head from 'next/head'
import Sigils from "../public/sigils/Sigils.js"

function PostList({posts}) {
    return (
    <>
    <Head>
        <title>ASOIAF wiki demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" href="/Kingsguard.ico"/>
    </Head>
    <div class="p-4 h-screen bg-zinc-900">
        <h1>List of pages made ({posts.length})</h1>
        <div class="flex flex-row gap-4 p-4 flex-wrap">
        {
            posts.map((post) => (
                <Link href={`/${post.id}`} passHref key={post.id}>
                    <div class="text-center flex flex-col bg-zinc-800 hover:bg-zinc-700 py-4 rounded-md text-sm w-40">
                        <h2>{post.title}</h2>
                        <Image 
                            alt={`${post.title} image`}
                            src={Sigils[post.houseInfo.content.coatOfArms.image]}
                            width="70"
                            className="mx-auto"
                        />
                    {post.houseInfo.type=="house"?<p>House page</p>:<p>Character page</p>}
                    </div>
                </Link>
            ))
        }</div>
    </div>
    </>
  )
}

export default PostList

export async function getStaticProps() {
    const response = await fetch("https://copper-chipmunk-gear.cyclic.app/POV")
    const data =  await response.json()

    return{
        props:{
            posts: data
        }
    }
}
